### PR TITLE
Add a basic block template for `mu-plugins` blocks

### PR DESCRIPTION
**Pull request by ryelle**
See #19.

This PR adds a template for generating a block to be used in [`wporg-mu-plugins`](https://github.com/WordPress/wporg-mu-plugins). The template can be used with `@wordpress/create-block`, and it will generate a block with the answers you give it.

The template is a forked version of the default `create-block` template — I've removed the overly-helpful comments, formatted the code with our code style, and removed the Sass from the `src` file. Now there's a separate `postcss` file which is where the CSS will live, as `*.pcss` to indicate that it's processed with PostCSS. Both `src` and `postcss` will be built down into a `build` folder (see https://github.com/WordPress/wporg-mu-plugins/pull/211 for the updated build process).

I kept this as basic as possible, so it really only provides a skeleton — if we find we need more structure after using it a bit, we can add it in to the template.

For an example, this will create a `new-block` folder with all the default values:

```bash
$ cd wporg-mu-plugins/mu-plugins/blocks
$ npx @wordpress/create-block -t "./vendor/wporg/wporg-repo-tools/templates/mu-block" new-block

Creating a new WordPress plugin in the "new-block" directory.

Creating a "block.json" file.

Creating a "package.json" file.

Done: WordPress plugin "New WordPress Block" bootstrapped in the "new-block" directory.

To enter the directory type:

  $ cd new-block

Code is Poetry
```

Now you have a new block, and you can open up the folder and see the generated code. The generated `README.md` has some instructions on how to finish setting this up in wporg-mu-plugins 

**To Test**

1. Check out this PR
2. Move to a directory where you can create a new folder
3. Run `npx @wordpress/create-block -t "/[SOME_PATH]/wporg-repo-tools/templates/mu-block"`
4. Answer the questions or leave them default
5. It should generate a folder
6. Open the new folder and read through the generated code

### CODE REVIEW

**Comment by StevenDufresne** [comment]
Yeah, I'm good with this. 👍

**Comment by StevenDufresne** [comment]
Should we add this repo to npm and add an entry point so we can use this via `npx`?

**Comment by ryelle** [comment]
This is just a template, the script used by `npx` is `create-block`. It looks like `create-block` could take a package name, so I guess we could create a package, but you can use it now with `npx` without that, since we have this repo as a composer dependency to all our other projects. After a `composer install` or `composer update`, you can just do this:

```
npx @wordpress/create-block -t "./vendor/wporg/wporg-repo-tools/templates/mu-block" new-block
```

**Comment by StevenDufresne** [comment]
> This is just a template, the script used by `npx` is `create-block`. It looks like `create-block` could take a package name, so I guess we could create a package, but you can use it now with `npx` without that, since we have this repo as a composer dependency to all our other projects. After a `composer install` or `composer update`, you can just do this:
> 
> ```
> npx @wordpress/create-block -t "./vendor/wporg/wporg-repo-tools/templates/mu-block" new-block
> ```

Yeah, I'm aware of that, it's just not a great interface and could be a bit error prone. For example, running the statement in the plugin folder gave me:

```
BongNam ~/dev/wp-github/wporg-mu-plugins/mu-plugins$ ls
total 24
drwxr-xr-x  10 stevendufresne  staff   320B Jul 22 15:07 .
drwxr-xr-x  18 stevendufresne  staff   576B Jul 26 21:52 ..
-rw-r--r--@  1 stevendufresne  staff   6.0K Jul 20 13:37 .DS_Store
drwxr-xr-x   6 stevendufresne  staff   192B Jul 26 20:33 blocks
drwxr-xr-x   7 stevendufresne  staff   224B Mar 23 12:26 global-fonts
-rw-r--r--   1 stevendufresne  staff   511B Jul 26 20:34 loader.php
drwxr-xr-x   4 stevendufresne  staff   128B Jul  7 14:23 plugin-tweaks
drwxr-xr-x   4 stevendufresne  staff   128B Jul  7 14:23 rest-api
drwxr-xr-x   3 stevendufresne  staff    96B Mar 23 12:26 skip-to
drwxr-xr-x   6 stevendufresne  staff   192B Jul  7 14:23 utilities
BongNam ~/dev/wp-github/wporg-mu-plugins/mu-plugins$ cd blocks/
BongNam ~/dev/wp-github/wporg-mu-plugins/mu-plugins/blocks$ npx @wordpress/create-block -t "./vendor/wporg/wporg-repo-tools/templates/mu-block" new-block
npx: installed 110 in 13.693s
Invalid plugin template type name: "./vendor/wporg/wporg-repo-tools/templates/mu-block". Allowed values: "es5", "static", or an existing npm package name.
```

A relative path will work however:
`npx @wordpress/create-block -t "../../vendor/wporg/wporg-repo-tools/templates/mu-block" new-block`

**Comment by adamwoodnz** [comment]
> npx @wordpress/create-block -t "./vendor/wporg/wporg-repo-tools/templates/mu-block" new-block

Where would be a good place to add documentation for this?

**Comment by ryelle** [comment]
Would the readme to this repo work? or maybe in [the team docs](https://github.com/automattic/neso-dev-docs)?

**Comment by adamwoodnz** [comment]
I always prefer repo. I find things stay more up to date when they live with the code

**Comment by StevenDufresne** [comment]
Can we use composer to execute it?

**Pull request merged**
